# Generated by Django 3.2.5 on 2021-08-08 04:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('희망픽업일', models.CharField(default=datetime.date.today, max_length=30, null=True)),
                ('희망픽업시간', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], default='10:00', max_length=30, null=True)),
                ('맛', models.CharField(choices=[('초콜릿', '초콜릿'), ('딸기', '딸기'), ('바닐라', '바닐라'), ('레드벨벳', '레드벨벳')], default='초콜릿', max_length=4, null=True)),
                ('모양', models.CharField(choices=[('원형', '원형'), ('하트', '하트'), ('사각형', '사각형')], default='원형', max_length=5, null=True)),
                ('사이즈', models.CharField(choices=[('도시락케이크(1~2인)', '도시락케이크(1~2인)'), ('1호(2~3인)', '1호(2~3인)'), ('2호(3~4인)', '2호(3~4인)'), ('3호(4~5인)', '2호(4~5인)')], default='도시락케이크', max_length=30, null=True)),
                ('크림종류', models.CharField(choices=[('버터', '버터'), ('생크림', '생크림'), ('크림치즈', '크림치즈')], default='버터', max_length=30, null=True)),
                ('레터링위치', models.CharField(choices=[('판 위에 레터링', '판 위에 레터링'), ('케이크에 직접 레터링', '케이크에 직접 레터링')], default='케이크에 직접 레터링', max_length=30, null=True)),
                ('레터링색', models.CharField(choices=[('RED', 'RED'), ('PINK', 'PINK'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE')], default='RED', max_length=30, null=True)),
                ('원하시는도안사진첨부', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('referred_cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.cake')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('store_image', models.ImageField(upload_to='storeimages/')),
                ('text', models.TextField(blank=True, default='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=15)),
                ('location', models.CharField(choices=[('종로구', '종로구'), ('중구', '중구'), ('용산구', '용산구'), ('성동구', '성동구'), ('광진구', '광진구'), ('동대문구', '동대문구'), ('중랑구', '중랑구'), ('성북구', '성북구'), ('강북구', '강북구'), ('도봉구', '도봉구'), ('노원구', '노원구'), ('은평구', '은평구'), ('서대문구', '서대문구'), ('마포구', '마포구'), ('양천구', '양천구'), ('강서구', '강서구'), ('구로구', '구로구'), ('금천구', '금천구'), ('영등포구', '영등포구'), ('동작구', '동작구'), ('관악구', '관악구'), ('서초구', '서초구'), ('강남구', '강남구'), ('송파구', '송파구'), ('강동구', '강동구')], default='마포구', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, default='')),
                ('rate', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.order', unique=True)),
                ('referred_cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.cake')),
                ('referred_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='referred_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_image', models.ImageField(blank=True, null=True, upload_to='cakeimages/')),
                ('referred_cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.cake')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='referred_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.store'),
        ),
    ]
