# Generated by Django 3.2.7 on 2021-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.CharField(default='10000', max_length=100),
        ),
    ]
