# Generated by Django 3.2.5 on 2021-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='meta_body',
            field=models.CharField(default='', max_length=100, verbose_name='검색을 위한 키워드(100자 이내)'),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_body',
            field=models.CharField(default='', max_length=100, verbose_name='검색을 위한 키워드(100자 이내)'),
        ),
    ]
