# Generated by Django 3.2.5 on 2021-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0002_auto_20210928_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountcoupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='percentcoupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
