# Generated by Django 3.2.5 on 2021-08-09 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakeManage', '0002_order_reviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_image',
            field=models.ImageField(null=True, upload_to='cakeimages/'),
        ),
        migrations.AddField(
            model_name='cake',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked_cake', related_query_name='users_liked_cake', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked_store', related_query_name='users_liked_store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cakeManage.order'),
        ),
        migrations.DeleteModel(
            name='CakeImage',
        ),
    ]
