# Generated by Django 3.2.5 on 2022-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0002_auto_20211123_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('img', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Cream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('img', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='menu_color', to='cakeManage.Menu_Color'),
        ),
        migrations.AddField(
            model_name='store',
            name='cream',
            field=models.ManyToManyField(blank=True, related_name='menu_color', to='cakeManage.Menu_Cream'),
        ),
    ]
