# Generated by Django 3.2.5 on 2022-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0003_auto_20220131_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_color',
            name='img',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu_color',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu_cream',
            name='img',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu_cream',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
