# Generated by Django 3.2.7 on 2021-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0003_alter_cake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(default='15000', max_length=100),
        ),
    ]
