# Generated by Django 3.2.5 on 2022-02-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0004_auto_20220201_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='color',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='cream',
            field=models.JSONField(null=True),
        ),
    ]
