# Generated by Django 3.2.5 on 2021-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0005_auto_20210810_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='원하시는도안사진첨부',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='사진 첨부(도시락케이크 선택시)'),
        ),
    ]
