# Generated by Django 3.2.5 on 2021-11-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0004_store_price'),
        ('cakeManage', '0006_auto_20211010_2128'),
    ]

    operations = [
    ]
