# Generated by Django 3.2.6 on 2021-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0006_alter_order_원하시는도안사진첨부'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
