# Generated by Django 3.2.5 on 2021-08-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0006_alter_order_원하시는도안사진첨부'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reviewing',
        ),
    ]
