# Generated by Django 3.2.6 on 2021-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0001_initial'),   
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.CharField(default=125.3, max_length=20, verbose_name='경도'),
        ),
    ]
        #('cakeManage', '0006_alter_order_원하시는도안사진첨부'),