# Generated by Django 3.2.5 on 2022-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0007_auto_20220204_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='색',
        ),
        migrations.RemoveField(
            model_name='order',
            name='크림종류',
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient',
            field=models.JSONField(default=dict),
        ),
    ]
