# Generated by Django 3.2.5 on 2021-08-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0007_remove_order_reviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewing',
            field=models.IntegerField(default=1),
        ),
    ]
