# Generated by Django 3.2.5 on 2022-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0008_auto_20220205_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store_Menu',
        ),
    ]
