# Generated by Django 3.2.9 on 2021-11-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0008_alter_cake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.CharField(choices=[('보틀', 'bottle'), ('도시락', 'dosirak'), ('1~2인분', '12'), ('3~4인분', '34'), ('5인분 이상', '5')], default='dosirak', max_length=10),
        ),
    ]
