# Generated by Django 3.2.6 on 2021-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0008_auto_20210814_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('검색단어', models.CharField(max_length=30)),
            ],
        ),
    ]
