# Generated by Django 3.2.6 on 2021-08-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0007_alter_store_name'),
        ('cakeManage', '0009_search'),
    ]

    operations = [
    ]
