# Generated by Django 3.2.9 on 2021-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0009_cake_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='size',
            field=models.CharField(choices=[('bottle', '보틀'), ('dosirak', '도시락'), ('12', '1~2인분'), ('34', '3~4인분'), ('5', '5인분 이상')], default='dosirak', max_length=10),
        ),
    ]
