# Generated by Django 3.2.6 on 2021-08-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0010_merge_0007_alter_store_name_0009_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location_si',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('대전', '대전'), ('세종', '세종'), ('충남', '충남'), ('충북', '충북'), ('부산', '부산'), ('울산', '울산'), ('경남', '경남'), ('경북', '경북'), ('대구', '대구'), ('광주', '광주'), ('전남', '전남'), ('전북', '전북'), ('제주', '제주')], default='서울', max_length=10),
        ),
    ]
