# Generated by Django 3.2.9 on 2021-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0011_auto_20211119_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='size',
            field=models.CharField(choices=[('보틀케이크', '보틀'), ('도시락케이크', '도시락'), ('1~2인분', '1~2인분'), ('3~4인분', '3~4인분'), ('5인분 이상', '5인분 이상')], default='dosirak', max_length=10),
        ),
    ]
