# Generated by Django 3.2.6 on 2021-08-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0012_alter_store_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='location_si',
            new_name='locationSi',
        ),
    ]
