# Generated by Django 3.2.6 on 2021-08-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0002_auto_20210819_2058'),
        ('cakeManage', '0013_rename_location_si_store_locationsi'),
    ]

    operations = [
    ]
