# Generated by Django 3.2.5 on 2021-08-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0014_merge_20210819_2119'),
        ('cakeManage', '0014_merge_20210819_2141'),
    ]

    operations = [
    ]
