# Generated by Django 3.2.9 on 2021-11-19 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0015_auto_20211119_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100000))]),
        ),
        migrations.AlterField(
            model_name='store',
            name='locationGu',
            field=models.CharField(default='노원구', max_length=10, verbose_name='구'),
        ),
    ]
