# Generated by Django 3.2.5 on 2021-11-20 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0016_alter_store_locationgu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prev_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
