# Generated by Django 3.2.9 on 2021-11-20 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0016_auto_20211120_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100000))], verbose_name='메뉴 평균 금액'),
        ),
    ]
