# Generated by Django 3.2.9 on 2021-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0017_alter_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='locationGu',
            field=models.CharField(default='00구/00시', max_length=10, verbose_name='지역(구/시)'),
        ),
    ]
