# Generated by Django 3.2.9 on 2021-11-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0017_order_prev_price'),
        ('cakeManage', '0018_alter_store_locationgu'),
    ]

    operations = [
    ]
