# Generated by Django 3.2.9 on 2021-11-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0019_merge_20211120_2314'),
        ('cakeManage', '0019_merge_20211121_0016'),
    ]

    operations = [
    ]
