# Generated by Django 3.2.9 on 2021-11-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeManage', '0020_alter_store_locationgu'),
        ('cakeManage', '0020_merge_20211121_0150'),
    ]

    operations = [
    ]
